FROM node:18-alpine

WORKDIR /app

# Install dependencies first to cache layer
COPY package.json .
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Start Vite development server
CMD ["npm", "run", "dev"]