#!/usr/bin/env python3
"""
Script to create a complete, runnable React Todo App.
Generated by CodeWriterAgent
"""
import os
import json
import sys

def create_file(path, content):
    """Helper function to create a file with given content."""
    try:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content.strip())
        print(f"  ✓ Created file: {os.path.basename(path)}")
    except IOError as e:
        print(f"  ✗ Error creating file {path}: {e}")
        raise

def main():
    """Main function to create the React Todo App project."""
    base_path = "/home/coder/project/"
    project_name = "react-todo-app"
    project_path = os.path.join(base_path, project_name)

    print(f"Creating project at: {project_path}")

    # ==========================================================================
    # Define File Contents
    # ==========================================================================

    package_json_content = {
        "name": "react-todo-app",
        "version": "0.1.0",
        "private": True,
        "dependencies": {
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "react-scripts": "5.0.1"
        },
        "scripts": {
            "start": "react-scripts start",
            "build": "react-scripts build",
            "test": "react-scripts test",
            "eject": "react-scripts eject"
        },
        "eslintConfig": {
            "extends": [
                "react-app",
                "react-app/jest"
            ]
        },
        "browserslist": {
            "production": [">0.2%", "not dead", "not op_mini all"],
            "development": ["last 1 chrome version", "last 1 firefox version", "last 1 safari version"]
        }
    }

    gitignore_content = """
    # See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

    # dependencies
    /node_modules
    /.pnp
    .pnp.js

    # testing
    /coverage

    # production
    /build

    # misc
    .DS_Store
    .env.local
    .env.development.local
    .env.test.local
    .env.production.local

    npm-debug.log*
    yarn-debug.log*
    yarn-error.log*
    """

    readme_content = """
    # React Todo App

    This project was bootstrapped programmatically.

    ## Available Scripts

    In the project directory, you can run:

    ### `npm install`

    Installs all the required dependencies for the application.

    ### `npm start`

    Runs the app in the development mode.\
    Open [http://localhost:3000](http://localhost:3000) to view it in the browser.

    The page will reload if you make edits.\
    You will also see any lint errors in the console.

    ### `npm run build`

    Builds the app for production to the `build` folder.\
    It correctly bundles React in production mode and optimizes the build for the best performance.
    """

    index_html_content = """
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />
        <meta
          name="description"
          content="Web site created using create-react-app"
        />
        <title>React Todo App</title>
      </head>
      <body>
        <noscript>You need to enable JavaScript to run this app.</noscript>
        <div id="root"></div>
      </body>
    </html>
    """

    index_js_content = """
    import React from 'react';
    import ReactDOM from 'react-dom/client';
    import './index.css';
    import App from './App';

    const root = ReactDOM.createRoot(document.getElementById('root'));
    root.render(
      <React.StrictMode>
        <App />
      </React.StrictMode>
    );
    """
    
    # We will just create a basic index.css to avoid an import error
    index_css_content = """
    body {
      margin: 0;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
        'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
        sans-serif;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      background-color: #f4f4f9;
    }

    code {
      font-family: source-code-pro, Menlo, Monaco, Consolas, 'Courier New',
        monospace;
    }
    """


    app_js_content = """
    import React, { useState, useEffect } from 'react';
    import './App.css';

    function App() {
      // Load todos from local storage or use a default array
      const [todos, setTodos] = useState(() => {
        const savedTodos = localStorage.getItem('todos');
        if (savedTodos) {
          return JSON.parse(savedTodos);
        } else {
          return [
            { id: 1, text: 'Learn React', completed: true },
            { id: 2, text: 'Build a Todo App', completed: false },
          ];
        }
      });
      const [input, setInput] = useState('');

      // Save todos to local storage whenever they change
      useEffect(() => {
        localStorage.setItem('todos', JSON.stringify(todos));
      }, [todos]);

      const handleInputChange = (e) => {
        setInput(e.target.value);
      };

      const handleAddTodo = (e) => {
        e.preventDefault();
        if (input.trim() === '') return;
        setTodos([
          ...todos,
          { id: Date.now(), text: input, completed: false }
        ]);
        setInput('');
      };

      const toggleTodo = (id) => {
        setTodos(
          todos.map(todo =>
            todo.id === id ? { ...todo, completed: !todo.completed } : todo
          )
        );
      };

      const deleteTodo = (id) => {
        setTodos(todos.filter(todo => todo.id !== id));
      };

      return (
        <div className="app-container">
          <div className="todo-app">
            <h1>Todo List</h1>
            <form onSubmit={handleAddTodo} className="todo-form">
              <input
                type="text"
                value={input}
                onChange={handleInputChange}
                placeholder="Add a new todo..."
                className="todo-input"
              />
              <button type="submit" className="todo-button">Add</button>
            </form>
            <ul className="todo-list">
              {todos.map(todo => (
                <li key={todo.id} className={todo.completed ? 'completed' : ''}>
                  <span onClick={() => toggleTodo(todo.id)} className="todo-text">
                    {todo.text}
                  </span>
                  <button onClick={() => deleteTodo(todo.id)} className="delete-button">✕</button>
                </li>
              ))}
            </ul>
          </div>
        </div>
      );
    }

    export default App;
    """

    app_css_content = """
    .app-container {
      display: flex;
      justify-content: center;
      align-items: flex-start;
      padding-top: 50px;
      min-height: 100vh;
      background-color: #f0f2f5;
    }

    .todo-app {
      background: #fff;
      width: 100%;
      max-width: 500px;
      padding: 30px;
      border-radius: 8px;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }

    h1 {
      color: #333;
      text-align: center;
      margin-bottom: 20px;
    }

    .todo-form {
      display: flex;
      margin-bottom: 20px;
    }

    .todo-input {
      flex-grow: 1;
      padding: 10px 15px;
      font-size: 16px;
      border: 2px solid #ddd;
      border-radius: 4px 0 0 4px;
      outline: none;
      transition: border-color 0.2s;
    }

    .todo-input:focus {
      border-color: #5b9dd9;
    }

    .todo-button {
      padding: 10px 20px;
      font-size: 16px;
      border: none;
      background: #5b9dd9;
      color: white;
      cursor: pointer;
      border-radius: 0 4px 4px 0;
      transition: background-color 0.2s;
    }

    .todo-button:hover {
      background: #4a8dcf;
    }

    .todo-list {
      list-style: none;
      padding: 0;
      margin: 0;
    }

    .todo-list li {
      display: flex;
      align-items: center;
      padding: 15px;
      background: #f9f9f9;
      border-bottom: 1px solid #eee;
      transition: background-color 0.2s;
    }

    .todo-list li:last-child {
      border-bottom: none;
    }

    .todo-list li.completed .todo-text {
      text-decoration: line-through;
      color: #aaa;
    }

    .todo-text {
      flex-grow: 1;
      cursor: pointer;
    }

    .delete-button {
      background: transparent;
      border: none;
      color: #ff4d4d;
      font-size: 20px;
      cursor: pointer;
      margin-left: 10px;
      opacity: 0;
      transition: opacity 0.2s;
    }

    .todo-list li:hover .delete-button {
      opacity: 1;
    }
    """

    try:
        # ======================================================================
        # Create Directories
        # ======================================================================
        print("Creating project directories...")
        public_path = os.path.join(project_path, 'public')
        src_path = os.path.join(project_path, 'src')
        os.makedirs(public_path, exist_ok=True)
        os.makedirs(src_path, exist_ok=True)
        print("  ✓ Directories created.")

        # ======================================================================
        # Create Files
        # ======================================================================
        print("\nCreating project files...")

        # Root files
        create_file(os.path.join(project_path, '.gitignore'), gitignore_content)
        create_file(os.path.join(project_path, 'README.md'), readme_content)
        with open(os.path.join(project_path, 'package.json'), 'w', encoding='utf-8') as f:
            json.dump(package_json_content, f, indent=4)
        print(f"  ✓ Created file: package.json")

        # Public files
        create_file(os.path.join(public_path, 'index.html'), index_html_content)

        # Src files
        create_file(os.path.join(src_path, 'index.js'), index_js_content)
        create_file(os.path.join(src_path, 'index.css'), index_css_content)
        create_file(os.path.join(src_path, 'App.js'), app_js_content)
        create_file(os.path.join(src_path, 'App.css'), app_css_content)

        print("\n✓ Project created successfully!")
        print("\nTo get started, run the following commands:")
        print(f"  cd {project_path}")
        print("  npm install")
        print("  npm start")
        return True

    except Exception as e:
        print(f"\n✗ Error creating project: {e}")
        return False


if __name__ == "__main__":
    if not main():
        sys.exit(1)
